### ISSUE TITLE
請問在Ubuntu 14.04.3上跑出現這樣的錯誤是正常的嗎?

### ISSUE THREAD

**Issue by windperson** [TrunkWorkshop/GebTestWithDocker#1]
<img width="960" alt="virtualbox_ubuntu_04_12_2015_16_31_29" src="https://cloud.githubusercontent.com/assets/1902259/11585122/998641e6-9aa4-11e5-8d04-e57780ecd0ae.png">
Groovy的版本是apt-get install安裝的：
Groovy Version: 1.8.6 JVM: 1.7.0_91 Vendor: Oracle Corporation OS: Linux
有看到Firefox打開瀏覽到google網站

**Comment by smlsunxie** [comment]
你可以把專案底下的 build folder 刪除再試試看

**Comment by windperson** [comment]
發現用SDK Man安裝的較新groovy v2.4.5就正常運作了，謝謝！
